# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec file for Linux Show Player (Windows portable build)
#
# To build on Windows:
#   pip install -r requirements-windows.txt
#   pyinstaller build_windows.spec --noconfirm --clean
#
# The output is dist/LinuxShowPlayer.exe  (single portable executable)

import os
from pathlib import Path

block_cipher = None
ROOT = Path(SPECPATH)


def collect_data(src_rel, dest_rel):
    """Return a datas tuple only if the source path exists."""
    src = ROOT / src_rel
    if src.exists():
        return (str(src), dest_rel)
    return None


# All data files that must be bundled inside the executable
_datas_raw = [
    # Core config
    collect_data("lisp/default.json", "lisp"),

    # UI themes (dark & light, including image assets)
    collect_data("lisp/ui/themes/dark",  "lisp/ui/themes/dark"),
    collect_data("lisp/ui/themes/light", "lisp/ui/themes/light"),

    # Icon themes
    collect_data("lisp/ui/icons/lisp",  "lisp/ui/icons/lisp"),
    collect_data("lisp/ui/icons/Numix", "lisp/ui/icons/Numix"),

    # Compiled Qt translations
    collect_data("lisp/i18n/qm", "lisp/i18n/qm"),

    # Plugin default configs
    collect_data("lisp/plugins/cache_manager/default.json",  "lisp/plugins/cache_manager"),
    collect_data("lisp/plugins/cart_layout/default.json",    "lisp/plugins/cart_layout"),
    collect_data("lisp/plugins/controller/default.json",     "lisp/plugins/controller"),
    collect_data("lisp/plugins/gst_backend/default.json",    "lisp/plugins/gst_backend"),
    collect_data("lisp/plugins/list_layout/default.json",    "lisp/plugins/list_layout"),
    collect_data("lisp/plugins/midi/default.json",           "lisp/plugins/midi"),
    collect_data("lisp/plugins/network/default.json",        "lisp/plugins/network"),
    collect_data("lisp/plugins/osc/default.json",            "lisp/plugins/osc"),
    collect_data("lisp/plugins/synchronizer/default.json",   "lisp/plugins/synchronizer"),
    collect_data("lisp/plugins/timecode/default.json",       "lisp/plugins/timecode"),
]

datas = [d for d in _datas_raw if d is not None]


# Hidden imports — every module loaded dynamically at runtime
hidden_imports = [
    # ── Core lisp modules ────────────────────────────────────────────────────
    "lisp",
    "lisp.application",
    "lisp.backend",
    "lisp.backend.audio_utils",
    "lisp.backend.backend",
    "lisp.backend.media",
    "lisp.backend.media_element",
    "lisp.backend.waveform",
    "lisp.command",
    "lisp.command.command",
    "lisp.command.cue",
    "lisp.command.layout",
    "lisp.command.model",
    "lisp.command.stack",
    "lisp.core",
    "lisp.core.class_based_registry",
    "lisp.core.clock",
    "lisp.core.configuration",
    "lisp.core.decorators",
    "lisp.core.dicttree",
    "lisp.core.fade_functions",
    "lisp.core.fader",
    "lisp.core.has_properties",
    "lisp.core.loading",
    "lisp.core.model",
    "lisp.core.model_adapter",
    "lisp.core.plugin",
    "lisp.core.plugin_loader",
    "lisp.core.properties",
    "lisp.core.proxy_model",
    "lisp.core.qmeta",
    "lisp.core.rwait",
    "lisp.core.session",
    "lisp.core.session_uri",
    "lisp.core.signal",
    "lisp.core.singleton",
    "lisp.core.util",
    "lisp.cues",
    "lisp.cues.cue",
    "lisp.cues.cue_factory",
    "lisp.cues.cue_model",
    "lisp.cues.cue_time",
    "lisp.cues.media_cue",
    "lisp.layout",
    "lisp.layout.cue_layout",
    "lisp.layout.cue_menu",

    # ── UI ───────────────────────────────────────────────────────────────────
    "lisp.ui",
    "lisp.ui.about",
    "lisp.ui.cuelistdialog",
    "lisp.ui.icons",
    "lisp.ui.layoutselect",
    "lisp.ui.logging",
    "lisp.ui.logging.common",
    "lisp.ui.logging.details",
    "lisp.ui.logging.dialog",
    "lisp.ui.logging.handler",
    "lisp.ui.logging.models",
    "lisp.ui.logging.status",
    "lisp.ui.logging.viewer",
    "lisp.ui.mainwindow",
    "lisp.ui.qdelegates",
    "lisp.ui.qmodels",
    "lisp.ui.settings",
    "lisp.ui.settings.app_configuration",
    "lisp.ui.settings.app_pages",
    "lisp.ui.settings.app_pages.cue",
    "lisp.ui.settings.app_pages.general",
    "lisp.ui.settings.app_pages.layouts",
    "lisp.ui.settings.cue_pages",
    "lisp.ui.settings.cue_pages.cue_appearance",
    "lisp.ui.settings.cue_pages.cue_general",
    "lisp.ui.settings.cue_pages.media_cue",
    "lisp.ui.settings.cue_settings",
    "lisp.ui.settings.pages",
    "lisp.ui.themes",
    "lisp.ui.themes.dark",
    "lisp.ui.themes.dark.dark",
    "lisp.ui.themes.dark.assets",
    "lisp.ui.themes.light",
    "lisp.ui.themes.light.light",
    "lisp.ui.ui_utils",
    "lisp.ui.widgets",
    "lisp.ui.widgets.colorbutton",
    "lisp.ui.widgets.cue_actions",
    "lisp.ui.widgets.cue_next_actions",
    "lisp.ui.widgets.digitalclock",
    "lisp.ui.widgets.dynamicfontsize",
    "lisp.ui.widgets.elidedlabel",
    "lisp.ui.widgets.fades",
    "lisp.ui.widgets.hotkeyedit",
    "lisp.ui.widgets.locales",
    "lisp.ui.widgets.pagestreewidget",
    "lisp.ui.widgets.qclicklabel",
    "lisp.ui.widgets.qclickslider",
    "lisp.ui.widgets.qeditabletabbar",
    "lisp.ui.widgets.qenumcombobox",
    "lisp.ui.widgets.qiconpushbutton",
    "lisp.ui.widgets.qmutebutton",
    "lisp.ui.widgets.qsteptimeedit",
    "lisp.ui.widgets.qstyledslider",
    "lisp.ui.widgets.qvertiacallabel",
    "lisp.ui.widgets.qwaitingspinner",
    "lisp.ui.widgets.waveform",

    # ── Plugins (all loaded dynamically by plugin_loader) ────────────────────
    "lisp.plugins",
    "lisp.plugins.action_cues",
    "lisp.plugins.action_cues.collection_cue",
    "lisp.plugins.action_cues.command_cue",
    "lisp.plugins.action_cues.index_action_cue",
    "lisp.plugins.action_cues.seek_cue",
    "lisp.plugins.action_cues.stop_all",
    "lisp.plugins.action_cues.volume_control",
    "lisp.plugins.cache_manager",
    "lisp.plugins.cache_manager.cache_manager",
    "lisp.plugins.cart_layout",
    "lisp.plugins.cart_layout.cue_widget",
    "lisp.plugins.cart_layout.layout",
    "lisp.plugins.cart_layout.model",
    "lisp.plugins.cart_layout.page_widget",
    "lisp.plugins.cart_layout.settings",
    "lisp.plugins.cart_layout.tab_widget",
    "lisp.plugins.controller",
    "lisp.plugins.controller.common",
    "lisp.plugins.controller.controller",
    "lisp.plugins.controller.controller_settings",
    "lisp.plugins.controller.protocol",
    "lisp.plugins.controller.protocols",
    "lisp.plugins.controller.protocols.keyboard",
    "lisp.plugins.controller.protocols.midi",
    "lisp.plugins.controller.protocols.osc",
    "lisp.plugins.list_layout",
    "lisp.plugins.list_layout.control_buttons",
    "lisp.plugins.list_layout.info_panel",
    "lisp.plugins.list_layout.layout",
    "lisp.plugins.list_layout.list_view",
    "lisp.plugins.list_layout.list_widgets",
    "lisp.plugins.list_layout.models",
    "lisp.plugins.list_layout.playing_view",
    "lisp.plugins.list_layout.playing_widgets",
    "lisp.plugins.list_layout.settings",
    "lisp.plugins.list_layout.view",
    "lisp.plugins.media_info",
    "lisp.plugins.media_info.media_info",
    "lisp.plugins.midi",
    "lisp.plugins.midi.midi",
    "lisp.plugins.midi.midi_cue",
    "lisp.plugins.midi.midi_io",
    "lisp.plugins.midi.midi_settings",
    "lisp.plugins.midi.midi_utils",
    "lisp.plugins.midi.port_monitor",
    "lisp.plugins.midi.widgets",
    "lisp.plugins.network",
    "lisp.plugins.network.api.cues",
    "lisp.plugins.network.api.layout",
    "lisp.plugins.network.discovery",
    "lisp.plugins.network.discovery_dialogs",
    "lisp.plugins.network.endpoint",
    "lisp.plugins.network.network",
    "lisp.plugins.network.server",
    "lisp.plugins.osc",
    "lisp.plugins.osc.osc",
    "lisp.plugins.osc.osc_cue",
    "lisp.plugins.osc.osc_delegate",
    "lisp.plugins.osc.osc_server",
    "lisp.plugins.osc.osc_settings",
    "lisp.plugins.presets",
    "lisp.plugins.presets.lib",
    "lisp.plugins.presets.presets",
    "lisp.plugins.presets.presets_ui",
    "lisp.plugins.rename_cues",
    "lisp.plugins.rename_cues.command",
    "lisp.plugins.rename_cues.rename_cues",
    "lisp.plugins.rename_cues.rename_ui",
    "lisp.plugins.synchronizer",
    "lisp.plugins.synchronizer.synchronizer",
    "lisp.plugins.timecode",
    "lisp.plugins.timecode.cue_tracker",
    "lisp.plugins.timecode.protocol",
    "lisp.plugins.timecode.protocols.midi",
    "lisp.plugins.timecode.settings",
    "lisp.plugins.timecode.timecode",
    "lisp.plugins.triggers",
    "lisp.plugins.triggers.triggers",
    "lisp.plugins.triggers.triggers_handler",
    "lisp.plugins.triggers.triggers_settings",

    # ── Third-party / stdlib hidden imports ─────────────────────────────────
    "mido",
    "mido.backends.rtmidi",
    "mido.backends.backend",
    "mido.messages",
    "mido.midifiles",
    "PyQt5.QtCore",
    "PyQt5.QtGui",
    "PyQt5.QtWidgets",
    "PyQt5.QtNetwork",
    "PyQt5.QtXml",
    "PyQt5.QtSvg",
    "PyQt5.QtPrintSupport",
    "PyQt5.sip",
    "pkg_resources",
    "pkg_resources.extern",
    "appdirs",
    "sortedcontainers",
    "sortedcontainers.sortedlist",
    "sortedcontainers.sorteddict",
    "qdigitalmeter",
    "falcon",
    "falcon.app",
    "falcon.request",
    "falcon.response",
    "requests",
    "requests.adapters",
    "requests.auth",
    "humanize",
    "numpy",
    "logging.handlers",
    "importlib.metadata",
    "importlib.resources",
    "json",
    "threading",
    "collections.abc",
]

# Modules to exclude — Linux-only or unavailable on Windows
excludes = [
    "pyalsa",
    "alsaseq",
    "jack",
    "pyliblo3",
    "liblo",
    "ola",
    # gi is provided by gi_stub at analysis time; exclude real GStreamer libs
    # but NOT gi itself — the stub lets PyInstaller trace code that imports gi.
    "lisp.plugins.gst_backend",
    "lisp.plugins.replay_gain",
    "lisp.plugins.timecode.protocols.artnet",
    "tkinter",
    "matplotlib",
    "scipy",
    "PIL",
    "test",
    "unittest",
    "xmlrpc",
    # NOTE: do NOT exclude 'distutils' — PyInstaller has its own hook that
    # aliases it; excluding it causes a ValueError during analysis.
]

a = Analysis(
    [str(ROOT / "lisp" / "main.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[str(ROOT / "windows_runtime_hook.py")],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="LinuxShowPlayer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=False,
)
